/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InvoiceProgram.View;

import javax.swing.JButton;
import javax.swing.JTable;

/**
 *
 * @author ACER
 */
public class Bank_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Bank
     */
    public Bank_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTab_Bank = new javax.swing.JTable();
        jBut_Delete = new javax.swing.JButton();
        jBut_Edit = new javax.swing.JButton();
        jBut_New = new javax.swing.JButton();
        jBut_Exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setBackground(new java.awt.Color(1, 77, 77));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cégnév - Bankok");
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setPreferredSize(new java.awt.Dimension(500, 30));
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jTab_Bank.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTab_Bank.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTab_Bank.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Név", "Swift kód", "Ország", "Cím"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTab_Bank.setSelectionBackground(new java.awt.Color(153, 153, 153));
        jTab_Bank.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTab_Bank);
        if (jTab_Bank.getColumnModel().getColumnCount() > 0) {
            jTab_Bank.getColumnModel().getColumn(0).setMinWidth(0);
            jTab_Bank.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTab_Bank.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jBut_Delete.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jBut_Delete.setText("Törlés");
        jBut_Delete.setPreferredSize(new java.awt.Dimension(90, 25));

        jBut_Edit.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jBut_Edit.setText("Megnyitás");
        jBut_Edit.setPreferredSize(new java.awt.Dimension(90, 25));
        jBut_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_EditActionPerformed(evt);
            }
        });

        jBut_New.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jBut_New.setText("Új adat");
        jBut_New.setPreferredSize(new java.awt.Dimension(90, 25));

        jBut_Exit.setBackground(new java.awt.Color(255, 128, 6));
        jBut_Exit.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jBut_Exit.setText("Kilépés");
        jBut_Exit.setBorder(new javax.swing.border.MatteBorder(null));
        jBut_Exit.setPreferredSize(new java.awt.Dimension(70, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBut_New, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBut_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBut_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBut_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBut_New, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBut_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBut_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBut_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBut_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_EditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBut_EditActionPerformed

    public JButton getjBut_Delete() {
        return jBut_Delete;
    }

    public void setjBut_Delete(JButton jBut_Delete) {
        this.jBut_Delete = jBut_Delete;
    }

    public JButton getjBut_Edit() {
        return jBut_Edit;
    }

    public void setjBut_Edit(JButton jBut_Edit) {
        this.jBut_Edit = jBut_Edit;
    }

    public JButton getjBut_Exit() {
        return jBut_Exit;
    }

    public void setjBut_Exit(JButton jBut_Exit) {
        this.jBut_Exit = jBut_Exit;
    }

    public JButton getjBut_New() {
        return jBut_New;
    }

    public void setjBut_New(JButton jBut_New) {
        this.jBut_New = jBut_New;
    }

    public JTable getjTab_Bank() {
        return jTab_Bank;
    }

    public void setjTab_Bank(JTable jTab_Bank) {
        this.jTab_Bank = jTab_Bank;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBut_Delete;
    private javax.swing.JButton jBut_Edit;
    private javax.swing.JButton jBut_Exit;
    private javax.swing.JButton jBut_New;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTab_Bank;
    // End of variables declaration//GEN-END:variables
}
