/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InvoiceProgram.View;

import javax.swing.JButton;
import javax.swing.JTable;

/**
 *
 * @author ACER
 */
public class Country_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Country
     */
    public Country_GUI() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTabl_Country = new javax.swing.JTable();
        jB_New = new javax.swing.JButton();
        jB_Edit = new javax.swing.JButton();
        jB_Delete = new javax.swing.JButton();
        jB_EXIT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setBackground(new java.awt.Color(1, 77, 77));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cégnév - Országok");
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 30));
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jTabl_Country.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTabl_Country.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Megnevezés", "Nyelv", "Aktív", "EU-tagság"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTabl_Country.setSelectionBackground(new java.awt.Color(153, 153, 153));
        jTabl_Country.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jTabl_Country);
        if (jTabl_Country.getColumnModel().getColumnCount() > 0) {
            jTabl_Country.getColumnModel().getColumn(0).setMinWidth(0);
            jTabl_Country.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTabl_Country.getColumnModel().getColumn(0).setMaxWidth(0);
            jTabl_Country.getColumnModel().getColumn(1).setMinWidth(250);
            jTabl_Country.getColumnModel().getColumn(1).setPreferredWidth(250);
            jTabl_Country.getColumnModel().getColumn(2).setMinWidth(50);
            jTabl_Country.getColumnModel().getColumn(2).setPreferredWidth(50);
            jTabl_Country.getColumnModel().getColumn(3).setMinWidth(75);
            jTabl_Country.getColumnModel().getColumn(3).setPreferredWidth(75);
        }

        jB_New.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jB_New.setText("Új adat");
        jB_New.setPreferredSize(new java.awt.Dimension(90, 25));

        jB_Edit.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jB_Edit.setText("Megnyitás");
        jB_Edit.setPreferredSize(new java.awt.Dimension(90, 25));

        jB_Delete.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jB_Delete.setText("Törlés");
        jB_Delete.setPreferredSize(new java.awt.Dimension(90, 25));

        jB_EXIT.setBackground(new java.awt.Color(255, 128, 6));
        jB_EXIT.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jB_EXIT.setText("Kilépés");
        jB_EXIT.setBorder(new javax.swing.border.MatteBorder(null));
        jB_EXIT.setPreferredSize(new java.awt.Dimension(70, 30));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jB_New, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jB_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jB_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jB_EXIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jB_New, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(jB_EXIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JTable getjTabl_Country() {
        return jTabl_Country;
    }

    public JButton getjB_Delete() {
        return jB_Delete;
    }

    public void setjB_Delete(JButton jB_Delete) {
        this.jB_Delete = jB_Delete;
    }

    public JButton getjB_EXIT() {
        return jB_EXIT;
    }

    public void setjB_EXIT(JButton jB_EXIT) {
        this.jB_EXIT = jB_EXIT;
    }

    public JButton getjB_Edit() {
        return jB_Edit;
    }

    public void setjB_Edit(JButton jB_Edit) {
        this.jB_Edit = jB_Edit;
    }

    public JButton getjB_New() {
        return jB_New;
    }

    public void setjB_New(JButton jB_New) {
        this.jB_New = jB_New;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Delete;
    private javax.swing.JButton jB_EXIT;
    private javax.swing.JButton jB_Edit;
    private javax.swing.JButton jB_New;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTabl_Country;
    // End of variables declaration//GEN-END:variables
}
