/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InvoiceProgram.View;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author ACER
 */
public class MainMenu2 extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu2
     */
    public MainMenu2() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jBt_MainMenu = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jBt_MasterData = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jBt_Settings = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jBt_Exit = new javax.swing.JButton();
        jPan_Main = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 204));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 169, 7));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 800));
        jPanel1.setLayout(new java.awt.GridLayout(5, 1, 30, 0));

        jPanel6.setBackground(new java.awt.Color(255, 169, 7));

        jBt_MainMenu.setBackground(new java.awt.Color(255, 128, 6));
        jBt_MainMenu.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jBt_MainMenu.setForeground(new java.awt.Color(255, 255, 255));
        jBt_MainMenu.setText("Főmenü");
        jBt_MainMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBt_MainMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBt_MainMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBt_MainMenu.setPreferredSize(new java.awt.Dimension(200, 40));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jBt_MainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jBt_MainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 169, 7));

        jBt_MasterData.setBackground(new java.awt.Color(255, 128, 6));
        jBt_MasterData.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jBt_MasterData.setForeground(new java.awt.Color(255, 255, 255));
        jBt_MasterData.setText("Törzsadatok");
        jBt_MasterData.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBt_MasterData.setPreferredSize(new java.awt.Dimension(200, 40));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jBt_MasterData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jBt_MasterData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        jPanel1.add(jPanel7);

        jPanel8.setBackground(new java.awt.Color(255, 169, 7));

        jBt_Settings.setBackground(new java.awt.Color(255, 128, 6));
        jBt_Settings.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jBt_Settings.setForeground(new java.awt.Color(255, 255, 255));
        jBt_Settings.setText("Beállítások");
        jBt_Settings.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBt_Settings.setPreferredSize(new java.awt.Dimension(200, 40));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jBt_Settings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jBt_Settings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        jPanel1.add(jPanel8);

        jPanel9.setBackground(new java.awt.Color(255, 169, 7));

        jBt_Exit.setBackground(new java.awt.Color(255, 128, 6));
        jBt_Exit.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jBt_Exit.setForeground(new java.awt.Color(255, 255, 255));
        jBt_Exit.setText("Kilépés");
        jBt_Exit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBt_Exit.setPreferredSize(new java.awt.Dimension(200, 40));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jBt_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jBt_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        jPanel1.add(jPanel9);

        getContentPane().add(jPanel1, java.awt.BorderLayout.WEST);

        jPan_Main.setBackground(new java.awt.Color(0, 102, 102));
        jPan_Main.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jPan_Main.setPreferredSize(new java.awt.Dimension(650, 800));

        javax.swing.GroupLayout jPan_MainLayout = new javax.swing.GroupLayout(jPan_Main);
        jPan_Main.setLayout(jPan_MainLayout);
        jPan_MainLayout.setHorizontalGroup(
            jPan_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        jPan_MainLayout.setVerticalGroup(
            jPan_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        getContentPane().add(jPan_Main, java.awt.BorderLayout.CENTER);
        jPan_Main.getAccessibleContext().setAccessibleName("jPanel2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getjBt_Exit() {
        return jBt_Exit;
    }

    public void setjBt_Exit(JButton jBt_Exit) {
        this.jBt_Exit = jBt_Exit;
    }

    public JButton getjBt_MainMenu() {
        return jBt_MainMenu;
    }

    public void setjBt_MainMenu(JButton jBt_MainMenu) {
        this.jBt_MainMenu = jBt_MainMenu;
    }

    public JButton getjBt_MasterData() {
        return jBt_MasterData;
    }

    public void setjBt_MasterData(JButton jBt_MasterData) {
        this.jBt_MasterData = jBt_MasterData;
    }

    public JButton getjBt_Settings() {
        return jBt_Settings;
    }

    public void setjBt_Settings(JButton jBt_Settings) {
        this.jBt_Settings = jBt_Settings;
    }

    public JPanel getjPan_Main() {
        return jPan_Main;
    }

    public void setjPan_Main(JPanel jPan_Main) {
        this.jPan_Main = jPan_Main;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBt_Exit;
    private javax.swing.JButton jBt_MainMenu;
    private javax.swing.JButton jBt_MasterData;
    private javax.swing.JButton jBt_Settings;
    private javax.swing.JPanel jPan_Main;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
