/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InvoiceProgram.View;

import javax.swing.JButton;

/**
 *
 * @author ACER
 */
public class PanelMasterData extends javax.swing.JPanel {



    /**
     * Creates new form PanelMasterData
     */
    public PanelMasterData() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBt_TaxYears = new javax.swing.JButton();
        jBt_Firm = new javax.swing.JButton();
        jBt_TaxCodes = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jB_Languages = new javax.swing.JButton();
        jB_Banks = new javax.swing.JButton();
        jB_BankAccount = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jB_PublicPlaces = new javax.swing.JButton();
        jB_Countires = new javax.swing.JButton();
        jB_Zips = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jB_Currencies = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 102));
        setPreferredSize(new java.awt.Dimension(600, 700));
        setLayout(new java.awt.GridLayout(5, 4, 30, 30));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jBt_TaxYears.setBackground(new java.awt.Color(1, 77, 77));
        jBt_TaxYears.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jBt_TaxYears.setForeground(new java.awt.Color(255, 255, 255));
        jBt_TaxYears.setText("Adóévek");
        jBt_TaxYears.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBt_Firm.setBackground(new java.awt.Color(1, 77, 77));
        jBt_Firm.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jBt_Firm.setForeground(new java.awt.Color(255, 255, 255));
        jBt_Firm.setText("Saját cég");
        jBt_Firm.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBt_TaxCodes.setBackground(new java.awt.Color(1, 77, 77));
        jBt_TaxCodes.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jBt_TaxCodes.setForeground(new java.awt.Color(255, 255, 255));
        jBt_TaxCodes.setText("Áfakulcsok");
        jBt_TaxCodes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jBt_Firm, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jBt_TaxYears, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jBt_TaxCodes, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBt_Firm, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBt_TaxYears, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBt_TaxCodes, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jB_Languages.setBackground(new java.awt.Color(1, 77, 77));
        jB_Languages.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jB_Languages.setForeground(new java.awt.Color(255, 255, 255));
        jB_Languages.setText("Nyelvek");
        jB_Languages.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jB_Banks.setBackground(new java.awt.Color(1, 77, 77));
        jB_Banks.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jB_Banks.setForeground(new java.awt.Color(255, 255, 255));
        jB_Banks.setText("Bankok");
        jB_Banks.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jB_Banks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_BanksActionPerformed(evt);
            }
        });

        jB_BankAccount.setBackground(new java.awt.Color(1, 77, 77));
        jB_BankAccount.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jB_BankAccount.setForeground(new java.awt.Color(255, 255, 255));
        jB_BankAccount.setText("Bankszámlák");
        jB_BankAccount.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jB_Banks, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                .addComponent(jB_Languages, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(223, 223, 223)
                    .addComponent(jB_BankAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(224, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_Banks, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_Languages, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(jB_BankAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(30, Short.MAX_VALUE)))
        );

        add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        jB_PublicPlaces.setBackground(new java.awt.Color(1, 77, 77));
        jB_PublicPlaces.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jB_PublicPlaces.setForeground(new java.awt.Color(255, 255, 255));
        jB_PublicPlaces.setText("Közterület");
        jB_PublicPlaces.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jB_Countires.setBackground(new java.awt.Color(1, 77, 77));
        jB_Countires.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jB_Countires.setForeground(new java.awt.Color(255, 255, 255));
        jB_Countires.setText("Országok");
        jB_Countires.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jB_Zips.setBackground(new java.awt.Color(1, 77, 77));
        jB_Zips.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jB_Zips.setForeground(new java.awt.Color(255, 255, 255));
        jB_Zips.setText("Irányítószámok");
        jB_Zips.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jB_Countires, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jB_PublicPlaces, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jB_Zips, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_Countires, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_PublicPlaces, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_Zips, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));

        jB_Currencies.setBackground(new java.awt.Color(1, 77, 77));
        jB_Currencies.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jB_Currencies.setForeground(new java.awt.Color(255, 255, 255));
        jB_Currencies.setText("Devizanemek");
        jB_Currencies.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jB_Currencies, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(411, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jB_Currencies, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        add(jPanel4);
    }// </editor-fold>//GEN-END:initComponents

    private void jB_BanksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_BanksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_BanksActionPerformed

    public JButton getjB_BankAccount() {
        return jB_BankAccount;
    }

    public void setjB_BankAccount(JButton jB_BankAccount) {
        this.jB_BankAccount = jB_BankAccount;
    }

    public JButton getjB_Banks() {
        return jB_Banks;
    }

    public void setjB_Banks(JButton jB_Banks) {
        this.jB_Banks = jB_Banks;
    }

    public JButton getjB_Countires() {
        return jB_Countires;
    }

    public void setjB_Countires(JButton jB_Countires) {
        this.jB_Countires = jB_Countires;
    }

    public JButton getjB_Currencies() {
        return jB_Currencies;
    }

    public void setjB_Currencies(JButton jB_Currencies) {
        this.jB_Currencies = jB_Currencies;
    }

    public JButton getjB_Languages() {
        return jB_Languages;
    }

    public void setjB_Languages(JButton jB_Languages) {
        this.jB_Languages = jB_Languages;
    }

    public JButton getjB_PublicPlaces() {
        return jB_PublicPlaces;
    }

    public void setjB_PublicPlaces(JButton jB_PublicPlaces) {
        this.jB_PublicPlaces = jB_PublicPlaces;
    }

    public JButton getjB_Zips() {
        return jB_Zips;
    }

    public void setjB_Zips(JButton jB_Zips) {
        this.jB_Zips = jB_Zips;
    }

    public JButton getjBt_Firm() {
        return jBt_Firm;
    }

    public void setjBt_Firm(JButton jBt_Firm) {
        this.jBt_Firm = jBt_Firm;
    }

    public JButton getjBt_TaxCodes() {
        return jBt_TaxCodes;
    }

    public void setjBt_TaxCodes(JButton jBt_TaxCodes) {
        this.jBt_TaxCodes = jBt_TaxCodes;
    }

    public JButton getjBt_TaxYears() {
        return jBt_TaxYears;
    }

    public void setjBt_TaxYears(JButton jBt_TaxYears) {
        this.jBt_TaxYears = jBt_TaxYears;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_BankAccount;
    private javax.swing.JButton jB_Banks;
    private javax.swing.JButton jB_Countires;
    private javax.swing.JButton jB_Currencies;
    private javax.swing.JButton jB_Languages;
    private javax.swing.JButton jB_PublicPlaces;
    private javax.swing.JButton jB_Zips;
    private javax.swing.JButton jBt_Firm;
    private javax.swing.JButton jBt_TaxCodes;
    private javax.swing.JButton jBt_TaxYears;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
